name: xo-5
services:
  client:
    container_name: xo_client
    build: ./xo_client
    ports:
      - '3000:3000'
    depends_on:
      - server

  server:
    container_name: xo_server
    build: ./xo_server
    ports:
      - '8000:8000'
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_DB: yourdbname
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - '443:443'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certs:/etc/ssl/certs
    depends_on:
      - client
      - server

volumes:
  postgres_data: