name: xo-5
services:
  client:
    container_name: xo_client
    build: ./xo_client
    ports:
      - '3000'
    depends_on:
      - server
    networks:
      - app-network

  server:
    container_name: xo_server
    build: ./xo_server
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
    ports:
      - '8000'
    depends_on:
      - db
    networks:
      - app-network

  db:
    container_name: postgres
    image: postgres:16.2-alpine3.19
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - '5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - '443:443'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certs:/etc/ssl/certs
    depends_on:
      - client
      - server
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge